# apiVersion: v2
# name: nginx # chart name
# version: 1.0.0 # chart version
# description: nginx helm chart
# appVersion: latest # this is application version

apiVersion: v2
name: nginx # chart name
version: 1.0.1 # chart version
description: upgrading to stable-perl version
appVersion: stable-perl # this is application version
