apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: {{ .Values.service.type }}
  selector:
    purpose: helm-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}  #service Port
      targetPort: 80 #container Port
      nodePort: 30007